name: Sidelobe Build Matrix Linux
on:
  workflow_call:
jobs:
  build:
    name: Linux, ${{matrix.cc}}, C${{matrix.cstd}}, ${{matrix.build_type}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cc:
          - gcc-9
          - gcc-12
        build_type: [Debug, Release]
        cstd: [99]
        std: [14]
        include:
          - cxx: g++-9
            cc: gcc-9
            other_pkgs: g++-9 gcc-9
          - cxx: g++-12
            cc: gcc-12
            other_pkgs: g++-12 gcc-12
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install Toolchain
      run: sudo apt-get install -y ${{matrix.other_pkgs}}
    - name: Setup & Cmake
      working-directory: deploy
      env:
        CC: ${{matrix.cc}}
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      # Note: $GITHUB_WORKSPACE is distinct from ${{runner.workspace}}.
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_C_STANDARD=${{matrix.cstd}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              ../..
        
    - name: Build & Run Tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: deploy/build
      run: |
        cmake --build . --parallel 2
        ctest -C ${{ matrix.build_type }} -L SelfRegisteringFactoryCTest -j 2
